# This is the DEVELOPMENT version of config_local.yml

# Database credentials.
database:
  driver: sqlite

# database:
#   driver: mysql
#   databasename: bolt
#   username: database_user
#   password: 'hunter42'

# Use development theme
theme: base-inuitcss_dev

# Debug settings
debug: true
debug_show_loggedoff: false
debug_error_level: -1
debug_error_use_symfony: false      # When set to true, Symfony Profiler will be used for exception display when possible

strict_variables: true
