# This file will be copied and renamed to `./www/.deploy.yml` so there's no
# need to edit that file directly. Also this file is used by both `rsync` and
# `simple` deploy methods. Simple deploy is only available in 3.4 beta for now.
# More details here: https://github.com/bolt/simple-deploy

staging:
    protocol: ftp
    options:
        host: example.com
        root: my-site
        username: deploy
        password: 'your password goes here'

production:
    protocol: sftp
    options:
        host: example.com
        username: deploy
        password: 'your password goes here'
        root: /var/www/sites/example.com
